import type { StyleTemplate } from '@/types'

export const STYLE_TEMPLATES: StyleTemplate[] = [
  {
    id: 'photorealistic',
    name: 'Photorealistic Scene',
    category: 'photorealistic',
    description: 'Create stunning photorealistic images with camera-specific details',
    icon: 'Camera',
    promptTemplate: 'A photorealistic {shot_type} of {subject}, {action}, set in {environment}. The scene is illuminated by {lighting}, creating a {mood} atmosphere. Captured with a {camera_details}, emphasizing {textures}.',
    examplePrompt: 'A photorealistic close-up portrait of an elderly Japanese ceramicist in their workshop, carefully shaping a clay bowl on a spinning wheel. The scene is illuminated by warm, diffused natural light streaming through a paper screen window, creating a serene and focused atmosphere. Captured with a Canon EOS R5, 85mm f/1.4 lens at f/2.0, emphasizing the deep wrinkles of the artisan\'s hands and the wet, smooth texture of the clay.',
  },
  {
    id: 'sticker',
    name: 'Sticker / Icon',
    category: 'illustration',
    description: 'Create kawaii-style stickers and icons with clean outlines',
    icon: 'Sticker',
    promptTemplate: 'A {style} sticker of a {subject}, featuring {characteristics} and a {color_palette}. The design should have {line_style} and {shading}. The background must be transparent.',
    examplePrompt: 'A kawaii-style sticker of a happy red panda holding a boba tea, featuring big sparkly eyes and rosy cheeks with a pastel pink and mint color palette. The design should have thick clean outlines and flat cel shading. The background must be transparent.',
  },
  {
    id: 'text-rendering',
    name: 'Text in Image',
    category: 'text-rendering',
    description: 'Generate images with accurate, legible text rendering',
    icon: 'Type',
    promptTemplate: 'Create a {image_type} for {brand} with the text "{text}" in a {font_style}. The design should be {style}, with a {color_scheme}.',
    examplePrompt: 'Create a modern, minimalist logo for a coffee shop called "The Daily Grind" with the text "THE DAILY GRIND" in a bold sans-serif font style. The design should be clean and geometric, with a warm brown and cream color scheme.',
  },
  {
    id: 'product-mockup',
    name: 'Product Mockup',
    category: 'product',
    description: 'Professional studio-quality product photography',
    icon: 'Package',
    promptTemplate: 'A high-resolution, studio-lit product photograph of a {product} on a {background}. The lighting is a {lighting_setup} to {purpose}. The camera angle is a {angle} to showcase {feature}. Ultra-realistic, with sharp focus on {detail}.',
    examplePrompt: 'A high-resolution, studio-lit product photograph of a minimalist ceramic coffee mug with a matte black finish on a polished concrete surface. The lighting is a three-point softbox setup to highlight the matte texture and subtle glaze. The camera angle is a 45-degree to showcase the handle design and interior glaze. Ultra-realistic, with sharp focus on the rim and handle junction.',
  },
  {
    id: 'minimalist',
    name: 'Minimalist Design',
    category: 'minimalist',
    description: 'Clean negative space compositions perfect for backgrounds',
    icon: 'Minus',
    promptTemplate: 'A minimalist composition featuring a single {subject} positioned in the {position} of the frame. The background is a vast, empty {color} canvas, creating significant negative space. Soft, subtle lighting.',
    examplePrompt: 'A minimalist composition featuring a single, delicate red maple leaf positioned in the bottom-right of the frame. The background is a vast, empty warm white canvas, creating significant negative space. Soft, subtle lighting with a gentle shadow.',
  },
  {
    id: 'comic-panel',
    name: 'Comic Panel',
    category: 'sequential',
    description: 'Create multi-panel comics and storyboards',
    icon: 'LayoutGrid',
    promptTemplate: 'Make a {panel_count} panel comic in a {style}. The character is {character}. {scene_description}.',
    examplePrompt: 'Make a 3 panel comic in a gritty, noir art style. The character is a detective in a trench coat. Panel 1: The detective walks down a rainy alley. Panel 2: They find a mysterious glowing object. Panel 3: Close-up of the detective\'s surprised face reflected in the glow.',
  },
  {
    id: 'search-grounded',
    name: 'Real-time Data Visual',
    category: 'search-grounded',
    description: 'Generate images based on current real-world information via Google Search',
    icon: 'Search',
    promptTemplate: 'Visualize {topic} as a {format}. Add {visual_elements}.',
    examplePrompt: 'Visualize the current weather forecast for the next 5 days in San Francisco as a clean, modern weather chart. Add visual suggestions for what to wear each day based on the conditions.',
  },
  {
    id: 'watercolor',
    name: 'Watercolor Painting',
    category: 'illustration',
    description: 'Soft, artistic watercolor-style illustrations',
    icon: 'Droplets',
    promptTemplate: 'A beautiful watercolor painting of {subject} with {color_palette}. The style features {technique} with {mood} mood.',
    examplePrompt: 'A beautiful watercolor painting of a Tuscan countryside with rolling hills and cypress trees with warm golden and olive green tones. The style features wet-on-wet blending with soft edges and paint blooms, with a peaceful, dreamy mood.',
  },
  {
    id: 'isometric',
    name: 'Isometric Scene',
    category: 'illustration',
    description: '3D isometric miniature worlds and cityscapes',
    icon: 'Box',
    promptTemplate: 'A clear, 45-degree top-down isometric miniature 3D cartoon scene of {subject}. Use soft, refined textures with realistic PBR materials and gentle lighting. {details}.',
    examplePrompt: 'A clear, 45-degree top-down isometric miniature 3D cartoon scene of a cozy Japanese ramen shop. Use soft, refined textures with realistic PBR materials and gentle lighting. Show the kitchen with a steaming pot, bar seating with tiny customers, and hanging lanterns outside.',
  },
  {
    id: 'magazine-cover',
    name: 'Magazine Cover',
    category: 'text-rendering',
    description: 'Professional magazine and publication covers',
    icon: 'BookOpen',
    promptTemplate: 'A photo of a glossy magazine cover with the title "{title}" in {font}. {description}. Include issue details in the corner with a barcode.',
    examplePrompt: 'A photo of a glossy magazine cover with the title "DIGITAL ARTISAN" in an elegant serif font. The cover features a portrait of a creative professional surrounded by floating holographic design elements. Include "Issue 42 - March 2026" and a barcode in the corner. The magazine is displayed on a modern shelf.',
  },
]
